FROM nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04
RUN mkdir /workspace
WORKDIR /workspace/
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y git nano libgl1-mesa-glx build-essential libglib2.0-0
RUN touch /root/.nanorc
RUN echo "set tabsize 4" >> ~/.nanorc
RUN echo "set tabstospaces" >> ~/.nanorc
COPY ./docker/Miniconda3-py38_4.10.3-Linux-x86_64.sh /root/Miniconda3-py38_4.10.3-Linux-x86_64.sh
RUN /root/Miniconda3-py38_4.10.3-Linux-x86_64.sh -b && eval "$(/root/miniconda3/bin/conda shell.bash hook)" && /root/miniconda3/bin/conda clean -afy 
RUN /root/miniconda3/bin/conda init
RUN echo 'conda activate real_robots' >> ~/.bashrc
COPY ./docker/environment_build.yml /root/environment.yml
RUN /root/miniconda3/bin/conda env create -f /root/environment.yml && /root/miniconda3/bin/conda clean -afy 
COPY ./docker/docker_evaluation.py /workspace/docker_evaluation.py
ADD . /workspace/
